# Generated by Django 5.0.2 on 2024-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_alter_car_manufacturer_alter_comment_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='other',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
