# Generated by Django 5.0.2 on 2024-02-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_manufacturer_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='other',
        ),
    ]
